### ISSUE TITLE
Visualización y gestión de usuarios/artistas

### ISSUE THREAD

**Issue by marcelarie** [apollofy-music-project/SongShare#50]
User Stories

- [ ] Vista de usuario #45
- [ ]  Seguir a otros usuarios #46
- [ ]  Visualización de seguidores #47
- [ ]  Visualización de siguiendo #48
