### ISSUE TITLE
Pantalla Home principal

### ISSUE THREAD

**Issue by marcelarie** [apollofy-music-project/SongShare#56]
User Stories

- [ ] Pantalla home básica #11
- [ ]  Sección “Playlists populares” en pantalla home #12
- [ ]  Sección “Artistas populares” en pantalla home #13
- [ ]  Sección “Playlists que sigo” en pantalla home #14
